### ISSUE TITLE
Does this still work with latest flask?

### ISSUE THREAD

**Issue by rlam3** [zzzsochi/Flask-Gravatar#21]
Does this still work with latest flask?

**Comment by jirikuncar** [comment]
@rlam3 it should :)

I have also refreshed the tests in https://github.com/zzzsochi/Flask-Gravatar/pull/22 and enabled regular checks on Travis CI.

**Comment by rlam3** [comment]
I was wondering if there was an extension to obtain the image url and pass it into an API as well...
