### ISSUE TITLE
config: read defaults from app config

### ISSUE THREAD

**Issue by jirikuncar** [zzzsochi/Flask-Gravatar#23]
Investigate possibility to read default configuration from `app.config` if not arguments are given to `Gravatar` constructor.

--
see https://github.com/zzzsochi/Flask-Gravatar/blob/master/flask_gravatar/__init__.py#L47-L67

**Comment by zzzsochi** [comment]
Sorry, last two months was get out from my brain.  :-)

If you want this feature — you do. I don't have time for this.

**Comment by jirikuncar** [comment]
I will prepare a PR.
